name: Code Coverage Checker

on:
  push:
  pull_request:
    types: [opened]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          cd tests
          COVERAGE_SCORE=$(./check_coverage.sh pytest | awk '$1 == "TOTAL" {print $NF+0}')
          COVERAGE_SCORE=$(($COVERAGE_SCORE+0))
          if [[ "$COVERAGE_SCORE" -lt "90" ]]; then 
            echo "Coverage is $COVERAGE_SCORE"
            exit 1
          fi
